### ISSUE TITLE
codeSign和属性中class关键字不识别

### ISSUE THREAD

**Issue by Longroader** [DSKcpp/PPAsyncDrawingKit#2]
第一个问题，CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.2'
第二个问题，有些属性里有class关键字，xcode不识别。
无法运行。

**Comment by DSKcpp** [comment]
第一个问题：真机运行，需要设置签名和 Team
第二个问题：class 关键字是 Xcode 8 的特性
