### ISSUE TITLE
重复造一个YYText轮子又不说明/another YYText copycat

### ISSUE THREAD

**Issue by LawrenceHan** [DSKcpp/PPAsyncDrawingKit#3]
重复造一个YYText轮子又不说明。。。
关键这个轮子我没看到有什么改进的地方。。。
这样骗赞好嘛

Looks like another YYText copycat.

**Comment by DSKcpp** [comment]
大家都是封装的CoreText，而且我和YY的逻辑完全是不一样的

**Comment by LawrenceHan** [comment]
不好意思，我重新花了半小时看了一下你的项目，但是我还是认为有抄袭嫌疑。结构太像了。

**Comment by DSKcpp** [comment]
因为CoreText 就是有 Layout Frame Line Run 组成的 这个结构是没法变的
